services:
  hugo:
    build: .
    container_name: hugo_server
    ports:
      - "2000:2000"
    volumes:
      - .:/app:cached
    networks:
      - hugo_network

networks:
  hugo_network:
    driver: bridge
