services:
  hugo:
    image: hugomods/hugo:latest
    container_name: hugo_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "2000:2000"
    command: ["server", "--bind", "0.0.0.0", "--port", "2000", "--watch"]

